- name: Ensure Elasticsearch package is installed
  apt:
    deb: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.7.0-amd64.deb
  register: elasticsearch_install

- name: Ensure Elasticsearch configuration is copied
  template:
    src: ./templates/elasticsearch.yml
    dest: /etc/elasticsearch/elasticsearch.yml
  notify: restart elasticsearch

- name: Ensure Elasticsearch service is started and enabled
  systemd:
    name: elasticsearch
    state: started
    enabled: yes

- name: Ensure Elasticsearch port is reachable
  wait_for:
    port: 9200