- name: restart elasticsearch
  systemd:
    name: elasticsearch
    state: restarted
    # Only restart Elasticsearch upon configuation changes if it was already installed
  when: not elasticsearch_install.changed

- name: restart kibana
  systemd:
    name: kibana
    state: restarted