---
- name: Apply OS updates to Elasticsearch and Kibana
  hosts: elasticsearch
  gather_facts: no
  vars:
    ansible_user: hunter
  tasks:
  - name: Upgrade all packages to the latest version
    apt:
      name: "*"
      state: latest
  